---
deployment:
  tasks:
    - export DEPLOYPATH=/home/u1008067/public_html/
    - /bin/cp index.html $DEPLOYPATH
    - /bin/cp asesuaula.html $DEPLOYPATH
    - /bin/cp blog.html $DEPLOYPATH
    - /bin/cp kompetisaun.html $DEPLOYPATH
    - /bin/cp kona-baMSA.html $DEPLOYPATH
    - /bin/cp mentor.html $DEPLOYPATH
    - /bin/cp prestasaun.html $DEPLOYPATH
    - /bin/cp -R assets $DEPLOYPATH